apiVersion: apps/v1
kind: Deployment
metadata:
  name: workervotacao
spec:
  selector:
    matchLabels:
      app: workervotacao
  replicas: 1
  template:
    metadata:
      labels:
        app: workervotacao
    spec:
      containers:
      - name: workervotacao
        image: renatogroffe/workerquestao-kafka-dotnet7:1
        env:
        - name: FeatureFlags__Monitoring
          value: "true"
        - name: FeatureFlags__PersistData
          value: "true"
        - name: ApacheKafka__Topic
          value: topic-interop
        - name: ApacheKafka__GroupId
          value: worker
        - name: ApacheKafka__Host
          value: resource.servicebus.windows.net:9093
        - name: ApacheKafka__Username
          valueFrom:
            secretKeyRef:
              name: workervotacaosecret
              key: UsernameKafka
        - name: ApacheKafka__Password
          valueFrom:
            secretKeyRef:
              name: workervotacaosecret
              key: PasswordKafka
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: workervotacaosecret
              key: AppInsightsConnection
        - name: ConnectionStrings__BaseVotacao
          valueFrom:
            secretKeyRef:
              name: workervotacaosecret
              key: SqlServerConnection