apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  UsernameKafka: $ConnectionString
  PasswordKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE 64>
  SaslKafka: plaintext
  TlsKafka: enable
  SqlServerConnection: <CONNECTION STRING DO SQL SERVER/AZURE SQL EM BASE 64>
  AppInsightsConnection: <CONNECTION STRING DO APPLICATION INSIGHTS EM BASE 64>